sonar.projectKey=Sistema-de-mejoramiento-Continuo-ELComite
sonar.organization=sgGuerra

# Project modules
sonar.modules=backend,frontend

# --- Backend Config ---
backend.sonar.projectName=Backend
backend.sonar.sources=app
backend.sonar.tests=tests
backend.sonar.language=py
backend.sonar.python.version=3.10
backend.sonar.python.coverage.reportPaths=coverage.xml

# --- Frontend Config ---
frontend.sonar.projectName=Frontend
frontend.sonar.sources=src
frontend.sonar.language=js,jsx
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Global Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/tests/**,**/*.config.js